language: php

php:
    - 5.3
    - 5.4
    - 5.5

branches:
    only:
        - solution

services: mongodb

before_script:
    - echo '' > ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
    - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - composer install --no-interaction

script:
    - bin/behat @TheCometCultOdysseyBundle
    - bin/phpspec run
notifications:
    email:
        - ks@thecometcult.com
        - jrl@thecometcult.com
