parameters:
    the_comet_cult_odyssey.mailer.config:
        crew.packing_instructions.template: TheCometCultOdysseyBundle:Mailer:crew_packing_instructions.email.twig
        from_email: 'no-reply@test.com'

services:
    the_comet_cult_odyssey.document_manager:
        class: Doctrine\ODM\MongoDB\DocumentManager
        factory_service: doctrine_mongodb
        factory_method: getManager
        public: false
    the_comet_cult_odyssey.mailer.message_factory:
        class: TheCometCult\OdysseyBundle\Mailer\MessageFactory
    the_comet_cult_odyssey.volunteer_repository:
        class: TheCometCult\OdysseyBundle\Repository\VolunteerRepository
        factory_service: doctrine_mongodb
        factory_method: getRepository
        arguments:
            - "TheCometCultOdysseyBundle:Volunteer"
    the_comet_cult_odyssey.log_repository:
        class: TheCometCult\OdysseyBundle\Repository\LogRepository
        factory_service: doctrine_mongodb
        factory_method: getRepository
        arguments:
            - "TheCometCultOdysseyBundle:Log"
    the_comet_cult_odyssey.success_rate_calculator:
        class: TheCometCult\OdysseyBundle\Calculator\SuccessRateCalculator
        arguments: ["@the_comet_cult_odyssey.log_repository"]
    the_comet_cult_odyssey.crew_manager:
        class: TheCometCult\OdysseyBundle\Manager\CrewManager
        arguments: ["@the_comet_cult_odyssey.document_manager", "@the_comet_cult_odyssey.volunteer_repository", "%the_comet_cult_odyssey.crew_size%", "@event_dispatcher"]
    the_comet_cult_odyssey.mission_manager:
        class: TheCometCult\OdysseyBundle\Manager\MissionManager
        arguments: ["@the_comet_cult_odyssey.document_manager", "@the_comet_cult_odyssey.time_manager", "@the_comet_cult_odyssey.houston"]
        calls:
            - [setLogger, ["@the_comet_cult_odyssey.logger"]]
    the_comet_cult_odyssey.houston:
        class: TheCometCult\OdysseyBundle\Mission\Checker\FoursquareChecker
        arguments: ["@foursquare_foursquare_api.checkin_manager"]
    the_comet_cult_odyssey.logger:
        class: TheCometCult\OdysseyBundle\Logger\MissionLogger
        arguments: ["@the_comet_cult_odyssey.document_manager"]
    the_comet_cult_odyssey.time_manager:
        class: TheCometCult\OdysseyBundle\Manager\TimeManager
        calls:
            - [setDepartureDelay, ["%the_comet_cult_odyssey.time.departure_delay%"]]
            - [setMissionEta, ["%the_comet_cult_odyssey.time.mission_eta%"]]
    the_comet_cult_odyssey.crew_manager_listener:
        class: TheCometCult\OdysseyBundle\EventListener\Manager\CrewManagerListener
        arguments: ["@the_comet_cult_odyssey.crew_manager"]
        tags:
            - { name: kernel.event_listener, event: volunteer.volunteer_registered, method: onVolunteerRegistered }
    the_comet_cult_odyssey.mission_manager_listener:
        class: TheCometCult\OdysseyBundle\EventListener\Manager\MissionManagerListener
        arguments: ["@the_comet_cult_odyssey.mission_manager"]
        tags:
            - { name: kernel.event_listener, event: crew.crew_created, method: onCrewCreated }
    the_comet_cult_odyssey.notification_mailer:
        class: TheCometCult\OdysseyBundle\Mailer\NotificationMailer
        arguments: ["@mailer"]
        calls:
            - [setMessageFactory, ["@the_comet_cult_odyssey.mailer.message_factory"]]
            - [setParameters, ["%the_comet_cult_odyssey.mailer.config%"]]
            - [setTemplating, ["@templating"]]
    the_comet_cult_odyssey.notification_listner:
        class: TheCometCult\OdysseyBundle\EventListener\Mailer\NotificationListner
        arguments: ["@the_comet_cult_odyssey.notification_mailer"]
        tags:
            - { name: kernel.event_listener, event: crew.crew_created, method: onCrewCreated }
